import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:flutter/material.dart';

final List<Map<String, dynamic>> availableIcons = [
  // Material Icons
  {'icon': Icons.fitness_center, 'name': 'fitness'},
  {'icon': Icons.book, 'name': 'book'},
  {'icon': Icons.water_drop, 'name': 'water'},
  {'icon': Icons.smoking_rooms, 'name': 'smoking'},
  {'icon': Icons.run_circle, 'name': 'run'},
  {'icon': Icons.self_improvement, 'name': 'meditation'},
  {'icon': Icons.sports_basketball, 'name': 'basketball'},
  {'icon': Icons.music_note, 'name': 'music'},
  {'icon': Icons.brush, 'name': 'art'},
  {'icon': Icons.code, 'name': 'coding'},

  // Material Design Icons (MdiIcons)
  {'icon': MdiIcons.yoga, 'name': 'yoga'},
  {'icon': MdiIcons.meditation, 'name': 'zen'},
  {'icon': MdiIcons.dumbbell, 'name': 'weights'},
  {'icon': MdiIcons.run, 'name': 'running'},
  {'icon': MdiIcons.bicycle, 'name': 'cycling'},
  {'icon': MdiIcons.swim, 'name': 'swimming'},
  {'icon': Icons.medication, 'name': 'medicine'},
  {'icon': MdiIcons.foodApple, 'name': 'healthy food'},
  {'icon': MdiIcons.bottleSoda, 'name': 'hydration'},
  {'icon': MdiIcons.sleep, 'name': 'sleep'},
  {'icon': MdiIcons.brain, 'name': 'mental'},
  {'icon': MdiIcons.bookOpen, 'name': 'reading'},
  {'icon': MdiIcons.guitarAcoustic, 'name': 'guitar'},
  {'icon': MdiIcons.piano, 'name': 'piano'},
  {'icon': MdiIcons.palette, 'name': 'art'},
  {'icon': MdiIcons.codeBrackets, 'name': 'programming'},
  {'icon': MdiIcons.signLanguage, 'name': 'language'},
  {'icon': MdiIcons.meditation, 'name': 'mindfulness'},
  {'icon': Icons.smoke_free, 'name': 'quit smoking'},
  {'icon': MdiIcons.bottleWine, 'name': 'quit drinking'},
  {'icon': MdiIcons.cash, 'name': 'saving'},
  {'icon': MdiIcons.phoneOff, 'name': 'digital detox'},
  {'icon': MdiIcons.socialDistance2Meters, 'name': 'social'},
  {'icon': MdiIcons.broom, 'name': 'cleaning'},
  {'icon': MdiIcons.weight, 'name': 'weight'},
  {'icon': MdiIcons.handHeart, 'name': 'self care'},
  {'icon': MdiIcons.toothbrush, 'name': 'dental'},
  {'icon': MdiIcons.coffee, 'name': 'coffee'},
  {'icon': MdiIcons.gamepad, 'name': 'gaming'},
  {'icon': MdiIcons.pen, 'name': 'writing'},
  {'icon': MdiIcons.clockOutline, 'name': 'time management'},
  {'icon': MdiIcons.accountGroup, 'name': 'social'},
  {'icon': MdiIcons.flashlight, 'name': 'wake up early'},
  {'icon': MdiIcons.weatherNight, 'name': 'sleep early'},
  {'icon': MdiIcons.foodForkDrink, 'name': 'diet'},
  {'icon': MdiIcons.medicalBag, 'name': 'vitamins'},
  {'icon': MdiIcons.walk, 'name': 'walking'},
  {'icon': MdiIcons.newspaper, 'name': 'reading news'},
  {'icon': MdiIcons.playlistMusic, 'name': 'practice'},
];
